CREATE TABLE `report_daily` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `timestamp` int(11) NOT NULL COMMENT '时间戳，当天的0点',
  `media_id` varchar(31) NOT NULL COMMENT '媒体id',
  `adspot_id` varchar(31) NOT NULL COMMENT '广告位id',
  `sdk_adspot_id` varchar(100) NOT NULL DEFAULT '-' COMMENT 'Sdk渠道的广告位id',
  `channel_id` varchar(31) NOT NULL COMMENT 'Sdk渠道的id',
  `pvs` bigint(20) NOT NULL DEFAULT '0' COMMENT '广告位请求数',
  `reqs` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道请求数',
  `bids` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道返回广告数',
  `wins` int(11) NOT NULL DEFAULT '0' COMMENT '渠道竞胜广告数',
  `shows` int(11) NOT NULL DEFAULT '0' COMMENT '渠道广告展现数',
  `clicks` int(11) NOT NULL DEFAULT '0' COMMENT '渠道广告点击数',
  `income` float NOT NULL DEFAULT '0' COMMENT '渠道广告收入',
  `report_api_req` int(11) NOT NULL DEFAULT '0' COMMENT 'ReportAPI 获取到的广告请求数',
  `report_api_bid` int(11) NOT NULL DEFAULT '0' COMMENT 'ReportAPI 获取到的广告返回数',
  `report_api_imp` int(11) NOT NULL DEFAULT '0' COMMENT 'ReportAPI 获取到的广告曝光数',
  `report_api_click` int(11) NOT NULL DEFAULT '0' COMMENT 'ReportAPI 获取到的广告点击数',
  `report_api_income` float NOT NULL DEFAULT '0' COMMENT 'ReportAPI 获取到的广告收入',
  PRIMARY KEY (`id`) USING HASH,
  UNIQUE KEY `uniKey` (`timestamp`,`media_id`,`adspot_id`,`sdk_adspot_id`,`channel_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=511 DEFAULT CHARSET=utf8